#!/bin/bash     

my_dir="$(dirname "$0")"

source $my_dir/janus_header

function usage {
    echo "Janus Function Coverage Timer"
    echo "Usage: "
    echo "./fcov <executable> [executable_args ...]"
}

if [ $# -lt "1" ]
then 
    usage
    exit
fi

binfile=$1
shift

hintfile="$binfile.jrs"
funcfile="$binfile.func"


if [ -f $binfile ];
then
   echo "Found executable $binfile"
else
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi

$JANUSBIN/analyze -ft $binfile
$TOOLDIR/bin64/drrun -ops "-opt_cleancall 3" -c $JANUSLIB/libgftimer.so @$hintfile @1 @1 -- $binfile $*
paste $funcfile func_cov.txt > $binfile.funccov.csv

rm $funcfile
rm func_cov.txt
