#!/bin/bash     
set -x
my_dir="$(dirname "$0")"

source $my_dir/janus_header

blue_color="\e[34m"
red_color="\e[31m"
bold_style="\e[1m"
reset="\e[0m"

function usage {
    echo "Address Sanitizer"
    echo "Usage: "
    echo "./jasan-dyn <executable> [executable_args ...]"
}

if [ $# -lt "1" ]
then 
    usage
    exit
fi

binfile=$1
shift
#shift
echo $binfile
if [ ! -f $binfile ];
then
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi

binname=$( echo "$binfile" | rev | cut -d'/' -f1 | rev )
scratchdir=/local/scratch/ma843
datadir=$scratchdir/rwdir-re
#datadir=/local/scratch/ma843/rwdir-re
#hintfile="$binfile.jrs" 
#hintfile="$binname.jrs" 
hintfile="$datadir/$binname.jrs"

echo -e "${bold_style}Binary: ${red_color} $binfile${reset}"
echo -e "${bold_style}RWSchedule: ${blue_color} $hintfile ${reset}"

if [ ! -f $hintfile ];
then 
   echo "WARNING:rewrite schedule not found. proceeding to dynamic only mode. STOP if not intended to go dynamic only"
   hintfile="dummy.jrs"
fi


LD_PRELOAD=$scratchdir/llvm-project/build/lib/clang/12.0.1/lib/linux/libclang_rt.asan-x86_64.so $TOOLDIR/bin64/drrun -no_vm_base_near_app -vm_base 0x200000000000  -c $JANUSLIB/libjasan.so @$hintfile @1 @0 -- $binfile $@
#LD_PRELOAD=/local/scratch/ma843/llvm-project/build/lib/clang/12.0.1/lib/linux/libclang_rt.asan-x86_64.so $TOOLDIR/bin64/drrun -debug -loglevel 2 -checklevel 0 -no_vm_base_near_app -vm_base 0x200000000000  -c $JANUSLIB/libjasan.so @$hintfile @1 @0 -- $binfile $@
