#!/bin/bash     
#set -x
my_dir="$(dirname "$0")"

source $my_dir/janus_header

function usage {
    echo "Address Sanitizer"
    echo "Usage: "
    echo "./jasan-stat <opt-option> <executable> [executable_args ...]"
}

if [ $# -lt "2" ]
then 
    usage
    exit
fi

stat_mode=$1
binfile=$2
#shift
#shift

blue_color="\e[34m"
red_color="\e[31m"
bold_style="\e[1m"
reset="\e[0m"

if [ ! -f $binfile ];
then
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi
echo $binfile | rev | cut -d/ -f1 | rev


scratchdir=/local/scratch/ma843
datadir=$scratchdir/rwdir-re
binname=$( echo "$binfile" | rev | cut -d'/' -f1 | rev )
hintfile=$datadir/$binname.jrs
asmfile="$datadir/$binname.s"

echo -e "${bold_style}Binary: ${red_color} $binfile${reset}"
echo -e "${bold_style}RWSchedule: ${blue_color} $hintfile ${reset}"
echo -e "${bold_style}asmfile: ${blue_color} $asmfile ${reset}"

if [ ! -f $asmfile ];
then
   objdump -d $binfile > $asmfile
fi
if [ $stat_mode == "opt" ];
then
    $JANUSBIN/analyze -aso $binfile
elif [ $stat_mode == "base" ];
then
    $JANUSBIN/analyze -as $binfile
elif [ $stat_mode == "live" ];
then
    $JANUSBIN/analyze -asl $binfile
elif [ $stat_mode == "scev" ];
then
    $JANUSBIN/analyze -asc $binfile
elif [ $stat_mode == "null" ];
then
    $JANUSBIN/analyze -asn $binfile
fi
#echo "$TOOLDIR/bin64/drrun -c $JANUSLIB/libjsbcets.so @$hintfile @1 @0 -- $binfile $*"
#gdb --args $TOOLDIR/bin64/drrun -debug -c $JANUSLIB/libjsbcets.so @$hintfile @1 @0 -- $binfile $@
