#!/bin/bash     

my_dir="$(dirname "$0")"

source $my_dir/janus_header

function usage {
    echo "Janus DSL Interpreter with Dynamic Library support"
    echo "Usage: "
    echo "./jdll <executable> [executable_args ...]"
}

if [ $# -lt "1" ]
then 
    usage
    exit
fi

binfile=$1
shift

hintfile="$binfile.jrs"

if [ -f $binfile ];
then
   echo "Found executable $binfile"
else
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi

$JANUSBIN/analyze -d $binfile

$TOOLDIR/bin64/drrun -ops "-opt_cleancall 3" -c $JANUSLIB/libjdll.so @$hintfile @1 @0 -- $binfile $*

