#!/bin/bash

my_dir="$(dirname "$0")"

source $my_dir/janus_header

function usage {
    echo "Guided Binary Memory Prefetcher"
    echo "Usage: "
    echo "./jfetch <executable> [executable_args ...]"
}

if [ $# -lt 1 ]
then 
  usage
  exit
fi

binfile=$1
shift
hintfile="$binfile.jrs"


if [ -f $binfile ];
then
   echo "Found executable $binfile"
else
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi

$JANUSBIN/analyze -f $binfile

time $TOOLDIR/bin64/drrun -c $JANUSLIB/libjfetch.so @$hintfile @1 @1 -- $binfile $@
#gdb --args $TOOLDIR/bin64/drrun -debug -c $JANUSLIB/libjfetch.so @$hintfile @1 @1 -- $binfile $@
