#!/bin/bash

my_dir="$(dirname "$0")"

source $my_dir/janus_header

#switch to older version of dynamoRIO for paralleliser
TOOLDIR="$DIR/../external/DynamoRIO-Linux-5.1.0-RC1/"

function usage {
    echo "Guided Binary Paralleliser without static analysis"
    echo "Usage: "
    echo "./jpar_dyn <number_of_threads> <executable> [executable_args ...]"
}

if [ $# -lt 2 ]
then 
  usage
  exit
fi

numthreads=$1
shift
binfile=$1
shift
hintfile="$binfile.jrs"
bininstr="$binfile.loop"

gdb --args $TOOLDIR/bin64/drrun -ops "-no_private_loader -thread_private" -c $GBRLIB/libjpar.so @$hintfile @$numthreads @1 -- $binfile $@
