#!/bin/bash     
#set -x
my_dir="$(dirname "$0")"

source $my_dir/janus_header

blue_color="\e[34m"
red_color="\e[31m"
bold_style="\e[1m"
reset="\e[0m"


function usage {
    echo "Janus Secure Execution with SOFTBOUND+CETS"
    echo "Usage: "
    echo "./jsbound <opt-option> <executable> [executable_args ...]"
    echo "./jasan <opt-option> <executable> [executable_args ...]"
    echo "opt-option: base, live, null"
}

if [ $# -lt "2" ]
then 
    usage
    exit
fi

stat_mode=$1
binfile=$2
shift
shift

if [ ! -f $binfile ];
then
   echo "Executable $binfile does not exist in the binaries folder."
   exit
fi

scratchdir=/local/scratch/ma843
datadir=$scratchdir/rwdir-sb
binname=$( echo "$binfile" | rev | cut -d'/' -f1 | rev )
hintfile=$datadir/$binname.jrs
asmfile="$datadir/$binname.s"
if [ ! -f $asmfile ];
then
   objdump -d $binfile > $asmfile
fi
echo -e "${bold_style}Binary: ${red_color} $binfile${reset}"
echo -e "${bold_style}RWSchedule: ${blue_color} $hintfile ${reset}"
echo -e "${bold_style}asmfile: ${blue_color} $asmfile ${reset}"

if [ $stat_mode == "live" ];
then
    $JANUSBIN/analyze -sl $binfile
elif [ $stat_mode == "base" ];
then
    $JANUSBIN/analyze -scet $binfile
elif [ $stat_mode == "null" ];
then
    $JANUSBIN/analyze -sn $binfile
fi
#asmfile="$datadir/$binname.s"
#echo "$TOOLDIR/bin64/drrun -c $JANUSLIB/libjguard.so @$hintfile @1 @0 -- $binfile $*"
#gdb --args $TOOLDIR/bin64/drrun -c $JANUSLIB/libjguard.so @$hintfile @1 @0 -- $binfile $@
$TOOLDIR/bin64/drrun -c $JANUSLIB/libjsbcets.so @$hintfile @1 @0 -- $binfile $@
#$TOOLDIR/bin64/drrun -max_bb_instrs 64 -c $JANUSLIB/libjsbcets.so @$hintfile @1 @0 -- $binfile $@
